name: Monitoraggio Asseverazioni Parziali

on:
  schedule:
    # Ogni lunedì alle 8:00 UTC (10:00 ora italiana)
    - cron: '0 8 * * 1'
  
  # Permetti esecuzione manuale per test
  workflow_dispatch:

jobs:
  monitor-asseverazioni:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pandas openpyxl requests
    
    - name: Download Excel file
      run: |
        # Il file verrà scaricato automaticamente da SharePoint tramite SHAREPOINT_URL
        # Non serve più scaricare manualmente
        echo "File Excel sarà scaricato automaticamente da SharePoint"
    
    - name: Run asseverazioni monitoring
      env:
        # Configurazione Gmail per invio email
        EMAIL_MITTENTE: 'federica.pazzolasatta@gmail.com'
        PASSWORD_EMAIL: 'ucbg rykk jptm xgyn'
        EMAIL_DESTINATARI: 'f.satta@innovazione.gov.it'
        # SHAREPOINT_URL: COMMENTATO per sicurezza
        # File locale CSV come unica fonte dati
        CSV_FILE_PATH: 'data/asseverazioni.csv'
      run: |
        python asseverazioni_reminder.py
    
    - name: Log completion
      run: |
        echo "✅ Monitoraggio asseverazioni completato il $(date)"
